[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"

[licenses]
unlicensed = "deny"
copyleft = "warn"
default = "deny"
allow = [
    "MIT",
    "BSD-3-Clause",
    "Apache-2.0",
    "Unicode-DFS-2016",
]
deny = []

[[licenses.exceptions]]
allow = ["GPL-3.0"]
name = "sw"

[bans]
wildcards = "deny"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
